# Generated by Django 4.2.26 on 2025-11-28 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estabelecimento',
            name='data_cadastro',
        ),
        migrations.CreateModel(
            name='PrecoCombustivel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_combustivel', models.CharField(choices=[('GASOLINA', 'Gasolina Comum'), ('GASOLINA_ADITIVADA', 'Gasolina Aditivada'), ('ETANOL', 'Etanol'), ('DIESEL', 'Diesel'), ('DIESEL_S10', 'Diesel S10')], max_length=20)),
                ('preco', models.DecimalField(decimal_places=3, max_digits=10)),
                ('data_coleta', models.DateTimeField(auto_now_add=True)),
                ('estabelecimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.estabelecimento')),
            ],
            options={
                'verbose_name': 'Preço de Combustível',
                'verbose_name_plural': 'Preços de Combustíveis',
            },
        ),
    ]
