# Generated by Django 4.2.26 on 2025-11-28 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_remove_estabelecimento_data_cadastro_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='precocombustivel',
            options={'ordering': ['-data_coleta'], 'verbose_name': 'Preço de Combustível', 'verbose_name_plural': 'Preços de Combustíveis'},
        ),
        migrations.AddField(
            model_name='precocombustivel',
            name='fonte',
            field=models.CharField(default='ANP', max_length=100),
        ),
        migrations.AlterField(
            model_name='precocombustivel',
            name='estabelecimento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='precos', to='myapp.estabelecimento'),
        ),
        migrations.AlterField(
            model_name='precocombustivel',
            name='preco',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='precocombustivel',
            name='tipo_combustivel',
            field=models.CharField(choices=[('GASOLINA_COMUM', 'Gasolina Comum'), ('GASOLINA_ADITIVADA', 'Gasolina Aditivada'), ('ETANOL', 'Etanol'), ('DIESEL', 'Diesel'), ('DIESEL_S10', 'Diesel S10'), ('GNV', 'GNV')], max_length=20),
        ),
    ]
