# Generated by Django 4.2.26 on 2025-11-28 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_precocombustivel_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='precocombustivel',
            name='fonte',
            field=models.CharField(default='Sistema', max_length=100),
        ),
    ]
