# Generated by Django 4.2.26 on 2025-12-03 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_precocombustivel_fonte'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='estabelecimento',
            options={'ordering': ['cidade', 'nome_fantasia'], 'verbose_name': 'Estabelecimento', 'verbose_name_plural': 'Estabelecimentos'},
        ),
        migrations.AddField(
            model_name='estabelecimento',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Ex: -23.550650', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='estabelecimento',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Ex: -46.633382', max_digits=9, null=True),
        ),
    ]
